backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"   # dove finiscono i file che carichi dal CMS
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home"
    file: "content/home.md"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
