backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"   # dove finiscono i file caricati dal CMS
public_folder: "/uploads"

collections:
  - name: "impostazioni"
    label: "Impostazioni sito"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Titolo pagina", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }
